# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fastElemMult <- function(X, Y) {
    .Call('_GFBioNet_fastElemMult', PACKAGE = 'GFBioNet', X, Y)
}

fastScale <- function(X) {
    .Call('_GFBioNet_fastScale', PACKAGE = 'GFBioNet', X)
}

cor2 <- function(X) {
    .Call('_GFBioNet_cor2', PACKAGE = 'GFBioNet', X)
}

getcor_fast <- function(X, G, cor_thresX, cor_thresG, cor_thresXG, xnames, gnames) {
    .Call('_GFBioNet_getcor_fast', PACKAGE = 'GFBioNet', X, G, cor_thresX, cor_thresG, cor_thresXG, xnames, gnames)
}

getcor_fast3 <- function(XG1ind_all, XG2ind_all, p) {
    .Call('_GFBioNet_getcor_fast3', PACKAGE = 'GFBioNet', XG1ind_all, XG2ind_all, p)
}

